version: '2'
services:
  transmission:
    image: dperson/transmission
    restart: ${HTPC_RESTART_POLICY}
    ports:
     - "9091:9091"
    command: -n
    volumes:
     - ${HTPC_HOME}/transmission:/var/lib/transmission-daemon/info
     - ${HTPC_HOME}/downloads:/var/lib/transmission-daemon/downloads
     - ${HTPC_HOME}/downloads-incomplete:/var/lib/transmission-daemon/incomplete
    environment:
     - USERID=${HTPC_USER_ID}
     - GROUPID=${HTPC_GROUP_ID}
     - TZ=${HTPC_TIMEZONE}
     - TRUSER=${HTPC_TRUSER}
     - TRPASSWD=${HTPC_TRPWD}

  couchpotato:
    image: linuxserver/couchpotato
    restart: ${HTPC_RESTART_POLICY}
    depends_on:
      - transmission
    ports:
     - "5050:5050"
    volumes:
     - ${HTPC_HOME}/couchpotato:/config
     - ${HTPC_HOME}/downloads:/downloads
     - ${HTPC_HOME}/media/Videos/Movies:/movies
    environment:
     - TZ=${HTPC_TIMEZONE}
     - PGID=${HTPC_GROUP_ID}
     - PUID=${HTPC_USER_ID}

  sickrage:
    image: linuxserver/sickrage
    restart: ${HTPC_RESTART_POLICY}
    depends_on:
      - transmission
    ports:
     - "8081:8081"
    volumes:
     - ${HTPC_HOME}/sickrage:/config
     - ${HTPC_HOME}/downloads:/downloads
     - ${HTPC_HOME}/media/Videos/TVShows:/tv
    environment:
     - TZ=${HTPC_TIMEZONE}
     - PGID=${HTPC_GROUP_ID}
     - PUID=${HTPC_USER_ID}

  mylar:
    image: linuxserver/mylar
    restart: ${HTPC_RESTART_POLICY}
    depends_on:
      - transmission
    ports:
     - "8090:8090"
    volumes:
     - ${HTPC_HOME}/mylar:/config
     - ${HTPC_HOME}/downloads:/downloads
     - ${HTPC_HOME}/media/comics:/comics
    environment:
     - TZ=${HTPC_TIMEZONE}
     - PGID=${HTPC_GROUP_ID}
     - PUID=${HTPC_USER_ID}

  emby:
    image: emby/embyserver
    restart: ${HTPC_RESTART_POLICY}
    ports:
     - "8096:8096"
     - "8920:8920"
     - "7359:7359"
     - "1900:1900"
    volumes:
     - ${HTPC_HOME}/emby:/config
     - ${HTPC_HOME}/media:/media     
    environment:
     - MB_USER_ID=${HTPC_USER_ID}
     - MB_GROUP_ID=${HTPC_GROUP_ID}
     - TZ=${HTPC_TIMEZONE}
     - AUTO_UPDATES_ON=true
